Examples require an initialized GsSession and relevant entitlements. External clients need to substitute thier own client id and client secret below. Please refer to [Authentication](https://developer.gs.com/p/docs/institutional/platform/authentication/) for details.

In [1]:
from gs_quant.session import GsSession

GsSession.use(client_id=None, client_secret=None, scopes=('read_product_data',))

In [2]:
from gs_quant.data import Dataset

In [3]:
# get the dataset
dataset = Dataset('EDRVOL_PERCENT_STANDARD')

### Dataset Coverage
Dataset coverage is a list of the symbol dimensions in a dataset. This allows users to quickly see what is available in a dataset.
Coverage can by fetched via API as below or in the [dataset product page](https://marquee.gs.com/s/developer/datasets/EDRVOL_PERCENT_STANDARD/coverage)

In [1]:
# get the coverage
coverage = dataset.get_coverage(include_history=True)

# show the number of records and columns
coverage.shape

(25, 4)

In [2]:
# show the columns names
coverage.keys()

Index(['bbid', 'assetId', 'name', 'historyStartDate'], dtype='str')

In [3]:
# show the coverage
coverage

       bbid  ... historyStartDate
0       AEX  ...       2018-06-03
1      IBOV  ...       2018-06-03
2      INDU  ...       2018-06-03
3       CAC  ...       2018-06-03
4       UKX  ...       2018-06-03
5       DAX  ...       2018-06-03
6     HSCEI  ...       2018-06-03
7       HSI  ...       2018-06-03
8    KOSPI2  ...       2018-06-03
9      MXEA  ...       2018-06-03
10     MXEF  ...       2018-06-03
11   MEXBOL  ...       2018-06-03
12      NKY  ...       2018-06-03
13      NDX  ...       2018-06-03
14      RTY  ...       2018-06-03
15  SPTSX60  ...       2018-06-03
16      SPX  ...       2018-06-03
17      SMI  ...       2018-06-03
18     SX5E  ...       2018-06-03
19      TPX  ...       2018-06-03
20   EEM UP  ...       2018-06-03
21   EFA UP  ...       2018-06-03
22   GLD UP  ...       2018-06-03
23   XLF UP  ...       2018-06-03
24   XLK UP  ...       2018-06-03

[25 rows x 4 columns]

In [4]:
# find specific asset
coverage[coverage['bbid'] == 'SPX']

   bbid              assetId           name historyStartDate
16  SPX  MA4B66MW5E27USPX001  S&P 500 Index       2018-06-03